- .gitignore
- Vagrantfile
- bootstrap.sh
- ngircd.conf
Creating a vagrant file for easy local development
> Add a vagrant development environment

- Legobot/__init__.py
This functionality will throttle how quickly it will send messages to a channel, to avoid being murdered by many obnoxious channels "Flood Protection". You set it with myBot.setThrottle(1), (in seconds)
> Added throttle

- Legobot/__init__.py
If the NICKPASS variable is empty, it will not attempt to auth with nickserv.
> Added NickServ functionality

- requirements.txt
> Added missing 'requests' module to requirements.txt

- Legobot/Lego.py
- Legobot/Legos/IRCConnector.py
- Legobot/Message.py
- Test/test_Message.py
Fixed some spacing issues to comply with PEP8. Also looks like one of the Message tests was incomplete, so I finished it off with an assert statement.
> PEP8 compliance and test fix

- Legobot/Legos/IRCConnector.py
> Add multichannel support for IRC lego

- Legobot/Connectors/IRC.py
@bbriggs This should mitigate the issue we saw/discussed on irc.
To refresh: voxpupuli/thevoxfox/issues/15 is the error.
> Handle decode errors.

- Legobot/Connectors/Slack.py
- Legobot/Legos/Help.py
> Message handling

- .travis.yml
> Second attempt at notifications

- Legobot/Connectors/IRC.py
- Legobot/Utilities.py
Or maybe 255... I don't even know anymore
> Send messages to IRC 256 chars at a time

- Legobot/Connectors/Slack.py
- Legobot/Legos/Help.py
- Legobot/Utilities.py
> Adding new function to the utilities package

- README.md
> Point Travis badges at proper location

- Legobot/Connectors/IRC.py
- Legobot/Connectors/Slack.py
- Legobot/LegoError.py
- Legobot/Utilities.py
> Misleading error

- Legobot/Connectors/Slack.py
As part of #157, @drewpearce discovered that Slack connector was not properly routing replies targeted for a user. This PR will fix that and close #159.
> Properly send route PMs to user in Slack connector

- Legobot/Connectors/Discord.py
- Legobot/Connectors/IRC.py
- Legobot/Connectors/Slack.py
> Connectors shouldn't try to send messages unless a target is specified

- README.md
- docs/intro.md
When I tried this bot for the first time, I noticed there are minor typo in the docs. This PR will fix some typos.
> Fixed IRC example on README.md and docs/intro.md

- .travis.yml
- Legobot/Connectors/Discord.py
- Legobot/Connectors/IRC.py
- Legobot/Connectors/Slack.py
adds metadata['user_id'] and metadata['display_name'] to each connector. Needs changelog and tagging to push release after merge.
> Add display names

- .travis.yml
- CHANGES.md
- setup.py
> Release 1.2.1

- Legobot/Connectors/Slack.py
> implement Slack client's autoconnect setting

- CHANGES.md
- Legobot/Connectors/Slack.py
- setup.py
Resolves #194.
This branch includes release prep (changes.md and setup.py)
Once merged we should be good for a release (1.2.3)
> Squash app source user bug

- Legobot/Lego.py
> Added convenience method for creating default options for reply messages.

- .gitignore
- CHANGES.md
- README.md
- setup.py
This is just README and .gitignore updates, but there are several contributor PRs that need to be merged to release. I will hold documentation (readme, changelog) and setup.py updates here for the release.
> Release 1.2.4

- .travis.yml
- CHANGES.md
- requirements-dev.txt
- requirements.txt
- setup.cfg
- setup.py
> Release 1.2.5

- .gitignore
- .travis.yml
- CHANGES.md
- Legobot/Connectors/Slack.py
- Legobot/Legos/Help.py
- setup.cfg
- Add timestamp and sub type to message metadata in Slack connector.
- Safer and more reliable Slack user name handling
- Help changes
- Only list Legos with names.
- Allow referencing Lego names in Help without regard to case.
> Release 1.2.6
